import type { Metadata } from "next";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import "./globals.scss";
import { montserrat } from "./fonts";
import React from "react";
import { MenuProvider } from "@/contexts/MenuContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <MenuProvider>
          <Header />
          {children}
          <Footer />
        </MenuProvider>
      </body>
    </html>
  );
}
